---
- name: Install
  sudo: true
  apt: pkg={{ item }}
  with_items:
  - apache2

- name: Enable modules
  sudo: true
  with_items:
  - rewrite
  - headers
  - expires
  command: a2enmod {{ item }}
- include: vhosts.yml