---
- name: Configure vhosts
  sudo: true
  with_items: apache.vhosts
  template:
    src="etc/apache2/sites-available/vhost.conf"
    dest="/etc/apache2/sites-available/{{ item.server_name }}.conf"

- name: Disable vhosts
  sudo: true
  command: a2dissite 000-default
  notify:
  - restart apache

- name: Enable vhosts
  sudo: true
  with_items: apache.vhosts
  command: a2ensite {{ item.server_name }}
  notify:
  - restart apache
