---
- name: Install MySQL
  sudo: true
  apt: pkg={{ item }}
  with_items:
  - mysql-server

- name: Install python Mysql package #required for mysql_db tasks
  sudo: true
  apt: name=python-mysqldb state=present

#- name: MySQL | Copy my.cnf file
#  sudo: true
#  notify:
#  - restart mysql
#  template:
#    src=my.cnf
#    dest="/etc/mysql/my.cnf"
#    owner=root
#    mode=0600
  
#- name: MySQL | Create database
#  with_items: mysql.credentials
#  mysql_db:
#    name={{ item.dbname }}
#    state=present
#
#- name: MySQL | Create users
#  with_items: mysql.credentials
#  mysql_user:
#    name="{{ item.username }}"
#    host="%"
#    password="{{ item.password }}"
#    priv="{{ item.dbname }}.*:ALL"
#    state=present