---
- name: Install phing
  sudo: true
  get_url:
    url="http://www.phing.info/get/phing-latest.phar"
    dest="/usr/bin/phing.phar"
    mode="0777"
- name: Symlink phing
  sudo: true
  file:
    src="/usr/bin/phing.phar"
    dest="/usr/bin/phing"
    state="link"
    mode="0777"